<?php
/**
 * User: xiaoqing Email: liuxiaoqing437@gmail.com
 * Date: 2017/3/27
 * Time: 下午3:37
 * 玩家反馈查询条件
 */

namespace App\Http\Components\ScopeCrm;

use App\Components\Helper\GeneralScope;
use App\Models\Crm\Reconciliation;

class ExchangeRate extends GeneralScope
{
    public $billing;
    public $currency;

    public function __construct(array $params, $user = null)
    {
        $this->billing = $params['billing'] ?? key(Reconciliation::getBilling());
        $this->currency = $params['currency'] ?? '';
        parent::__construct($params, $user);
    }

    public function setWhere($tableAlias = null, $excludes = [])
    {
        parent::setWhere($tableAlias); // TODO: Change the autogenerated stub
        $this->where = '1 = 1 ';
        if (!empty($this->billing)) {
            $where[] = sprintf("%sbilling_cycle = '%s'", $tableAlias, $this->billing);
        }

        if (!empty($this->currency)) {
            $where[] = sprintf("%scurrency = '%s'", $tableAlias, $this->currency);
        }
        $this->where = empty($where) ? $this->where : sprintf('%s AND %s', $this->where, implode(' AND ', $where));
    }
}