<?php
/**
 * User: xiaoqing Email: liuxiaoqing437@gmail.com
 * Date: 2017/3/27
 * Time: 下午3:37
 * 玩家反馈查询条件
 */

namespace App\Http\Components\ScopeCrm;

use App\Components\Helper\GeneralScope;

class Principal extends GeneralScope
{
    public $product;

    public function __construct(array $params, $user = null)
    {
        $this->product = $params['product'] ?? '';
        parent::__construct($params, $user);
    }

    public function setWhere($tableAlias = null, $excludes = [])
    {
        parent::setWhere($tableAlias); // TODO: Change the autogenerated stub
        $this->where = '1 = 1 ';
        if (!empty($this->product)) {
            $where[] = sprintf('%sproduct = %d', $tableAlias, $this->product);
        }
        $this->where = empty($where) ? $this->where : sprintf('%s AND %s', $this->where, implode(' AND ', $where));
    }
}