<?php
/**
 * User: xiaoqing Email: liuxiaoqing437@gmail.com
 * Date: 2017/3/27
 * Time: 下午3:37
 * 玩家反馈查询条件
 */

namespace App\Http\Components\ScopeCrm;

use App\Components\Helper\GeneralScope;

class Reconciliation extends GeneralScope
{
    public function __construct(array $params, $user = null)
    {
        parent::__construct($params, $user);
    }

    public function setWhere($tableAlias = null, $excludes = [])
    {
        parent::setWhere($tableAlias); // TODO: Change the autogenerated stub
    }
}